version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  orderDb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  ecommerce.catalog.api:
    image: ${DOCKER_REGISTRY-}ecommercecatalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/ECommerce.Catalog.API/Dockerfile

  ecommerce.basket.api:
    image: ${DOCKER_REGISTRY-}ecommercebasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/ECommerce.Basket.API/Dockerfile

  ecommerce.discount.grpc:
    image: ${DOCKER_REGISTRY-}ecommercediscountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/ECommerce.Discount.Grpc/Dockerfile

  ecommerce.ordering.api:
    image: ${DOCKER_REGISTRY-}ecommerceorderingapi
    build:
      context: .
      dockerfile: src/Services/Ordering/ECommerce.Ordering.API/Dockerfile

  ecommerce.api.gateway:
    image: ${DOCKER_REGISTRY-}ecommerceapigateway
    build:
      context: .
      dockerfile: src/ApiGateways/ECommerce.API.Gateway/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
