version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  orderDb:
    image: mcr.microsoft.com/mssql/server

  ecommerce.catalog.api:
    image: ${DOCKER_REGISTRY-}ecommercecatalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/ECommerce.Catalog.API/Dockerfile

  ecommerce.basket.api:
    image: ${DOCKER_REGISTRY-}ecommercebasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/ECommerce.Basket.API/Dockerfile


  ecommerce.discount.grpc:
    image: ${DOCKER_REGISTRY-}ecommercediscountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/ECommerce.Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:


